---
title: "Testing"
author: "Alexandra Niessl"
date: "12/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Context

(where this will be used later)

## Objective
This function simulates data from an illness-death model with one row per transition and subject
Input parameters:
N: Number of patients
alpha01:  initial to progression transition hazard
alpha02:  initial to death transition hazard
alpha12:  progression to death transtion hazard
...

## Prototype

```{r prototype}

# getSimulatedData<-function(N,
#                            alpha01,alpha02,alpha12, 
#                            p01=1,p02=1,p12=1, 
#                            pwT01=0,pwT02=0,pwT12=0,
#                            dropoutRate=0, dropTime=0,accrualIntensity=0,accrualTime=0){

library(checkmate)

assert_positive_number <- function(x) {
  assert_number(x)
  assert_true(x > 0)
}

exponential_transition <- function(h01, h02, h12) {
  assert_positive_number(h01)
  assert_positive_number(h02)
  assert_positive_number(h12)
  structure(
    list(
      hazards = list(h01 = h01, h02 = h02, h12 = h12),
      intervals = list(p01 = 0, p02 = 0, p12 = 0),
      weibull_rates = list(p01 = 1, p02 = 1, p12 = 1)
    ),
    class = "TransitionParameters"
  )
}

test <- exponential_transition(1, 1, 1)
class(test)

print.TransitionParameters <- function(object) {
  cat("Transition Parameters for Simulations\n")
  cat("hazards:", unlist(object$hazards))
}

test

piecewise_constant <- function() {
  
}

weibull_transition <- function(hazards, weibull_rates) {
  list(
    transition_hazards = list(h01 = 1, h02 = 1, h12 = 1),
    weibull_rates = list(p01 = 1,p02 =1,p12=1),
    hazard_intervals = list(p01 = 0,p02 = 0,p12 = 0),
  )
}

 
#' Title
#'
#' @param N (`int`)\cr number of patients.
#' @param transition (`TransitionParameters`)\cr transition parameters comprising 
#'   `hazards`, corresponding `intervals` and `weibull_rates`, see ...
#' @param dropout 
#' @param accrual 
#' 
#'
#' @return
#' @export
#'
#' @examples
getSimulatedData<-function(N,
                           transition = exponential_transition(h01 = 1, h02 = 1, h12 = 1),
                           dropout = list(rate = 0, time = 0),
                           accrual = list(intensity = 0, time = 0)) {
  assert_int(N, lower = 1L)
  assert_class(transition_parameters, "TransitionParameters")
  
  #get rate parameter for exponential distributed censoring times
  if(dropoutRate != 0){
    censRate<-  -log(1-dropoutRate)/dropTime
    #get censoring times
    censTime<-rexp(N, censRate)
  }
  
  ###all individuals start in the initial state
  entry<-rep(0,N)
  from<-rep(0,N)
  
  ###Waiting time in the initial state 0 
  U<-runif(N)
  
  ##for exponential or Weibull
  if(length(alpha02)==1&length(alpha01)==1){
    wait_time<- getWaitTimeSum(N,U,alpha01,alpha02,p01,p02,max.int=10000,entry)  
    ###binomial experiment decides on death or progression
    numerator<-p01*alpha01^p01*wait_time^(p01-1)
    denumerator<-numerator+p02*alpha02^p02*wait_time^(p02-1)
 
  ##for piecewise constant
   }else{
    wait_time<- pcw(N,U, getSumPCW(alpha01, alpha02,pwT01, pwT02), 
                    unique(sort(c(pwT01,pwT02))),entry)
    ###binomial experiment decides on death or progression
    numerator<-getPCWHazard(alpha01,pwT01,wait_time)
    denumerator<-getPCWHazard(alpha01,pwT01,wait_time)+getPCWHazard(alpha02,pwT02,wait_time)
  }
  
  to_prob <- rbinom(N,1, numerator/denumerator)
  to<- ifelse(to_prob==0,2,1)
  exit<-wait_time
  
  ##add censoring
  if(dropoutRate != 0){
    to<-ifelse(censTime< wait_time, "cens", to)  
    exit<-pmin(censTime,wait_time)
  }
  simData<-data.frame(id=1:N, from=from, to=to, entry=entry, exit=exit,stringsAsFactors = FALSE)
  
  ###1->2 transition
  id1<-simData$id[simData$to==1]
  if(length(id1)!=0){
    N1<-length(id1)
    U1<-runif(N1)
    to1<-rep(2,N1)
    from1<-rep(1,N1)
    entry1<-simData$exit[simData$id %in% id1]
    
    ##Wait time in state 1
    ##exponential 
    if(length(alpha12)==1 & p12==1){
      wait_time1<- (-log(1-U1))/(alpha12)
     
    ##Weibull
    }else if(length(alpha12)==1){
      wait_time1<- getWaitTimeSum(N1,U1,alpha12,alpha02=0,p12,p02=1,max.int=1000,entry=entry1)
    
    #piecewise
    }else{
      wait_time1<- pcw(N1,U1,haz=alpha12, cuts=pwT12,t_0=entry1)
    }

    exit1<-entry1+wait_time1
  
    ##add censoring
    if(dropoutRate != 0){ 
      censTime1<-censTime[id1]
      to1<-ifelse(censTime1< exit1, "cens", to1)  
      exit1<-pmin(censTime1,exit1)
    }
    newRows<-data.frame(id=id1, from=from1, to=to1, entry=entry1, exit=exit1,stringsAsFactors = FALSE)
    simData<-rbind(simData,newRows)
  }  
  
  simData<- simData[order(simData$id),]
  
  ###add staggered study entry
  ##get accrual times
  if(accrualTime != 0){
    entry_act<-runif(N,0,accrualTime)
  }
  if(accrualIntensity !=0 & accrualTime==0){
    accrualTime<-N/accrualIntensity 
    entry_act<-runif(N,0,accrualTime)
  } 
  else{
    entry_act=rep(0,N)
  }
  
  entryAct<-cbind(id=1:N,entry_act)
  
  simData<-merge(simData, entryAct)
  exitAct<-simData$exit+simData$entry_act
  entryAct<-simData$entry+simData$entry_act
  if(dropoutRate != 0){
    censAct<-censTime+entry_act
    simData<-merge(simData, cbind(id=1:N, censAct))
  } 
  simData<-cbind(simData,  entryAct, exitAct)
  simData[,c("entry_act")]<-list(NULL)
  return(simData)
} 

```

## Helper functions

```{r}
# put here
```


## Try it out

```{r}
# 1-2 examples
```

